name: Exemplo de Workflow acionado por Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Run script
      run: echo "O código foi atualizado!"

      


