---
name: Workflow a cada hora

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  job_example:
    runs-on: ubuntu-latest
    steps:
    - name: Exemplo de etapa 1
      run: echo "Executando a cada hora"


---

name: Exemplo de Workflow acionado por Push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      
    - name: Run script
      run: echo "O código foi atualizado!"

      


